name: Release

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
      - next # or next branch

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*" # Use a compatible Node.js version
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci
      - name: Audit Signatures
        run: npm audit signatures

      # Run semantic release
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Add this to your GitHub repository secrets
        run: npx semantic-release
