name: Release

on:
  push:
    branches:
      - main
      - next

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Use latest Bun version

      # Verify Bun installation
      - name: Check Bun version
        run: bun --version

      # Install dependencies (including devDependencies)
      - name: Install dependencies
        run: bun install --development

      # Ensure semantic-release is installed
      - name: Install semantic-release and plugins
        run: bun add -d semantic-release @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/changelog

      # Run semantic release
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Add this to your GitHub repository secrets
        run: bunx semantic-release
