name: Release

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use a compatible Node.js version
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run semantic release
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Add this to your GitHub repository secrets
        run: npx semantic-release
